version: '3'
services:
  django:
    build: ./app
    command: >
      bash -c "python3 manage.py makemigrations && python3 manage.py migrate && uwsgi --ini uwsgi.ini"
    env_file:
      - app/.env
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    image: postgres:15
    container_name: team-up-iq-test
    volumes:
      - .pg_data:/var/lib/postgresql/data
    env_file:
      - app/.env
    ports:
      - '5432:5432'