services:
  postgres_db:
    image: postgres:15
    container_name: team-up-postgres
    volumes:
      - .pg_data:/var/lib/postgresql/data
    env_file:
      - app/.env
    ports:
      - '5432:5432'

  django:
    build: ./app
    container_name: team-up-django
    env_file:
      - app/.env
    ports:
      - '8000:8000'
    depends_on:
      - postgres_db
    restart: always

  swagger:
    image: swaggerapi/swagger-ui
    container_name: team-up-swagger-ui
    volumes:
      - ./openapi/openapi.yaml:/swagger.yaml
    environment:
      -  SWAGGER_JSON=/swagger.yaml
    ports:
      - '8089:8080'
