# Generated by Django 3.2 on 2023-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iqtest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='iqtest',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
