# Generated by Django 3.2 on 2023-06-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230609_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iqtest',
            old_name='test_id',
            new_name='test',
        ),
    ]
