# Generated by Django 3.2 on 2023-06-10 00:48

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_iqtest_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='EQTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('result', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), size=5)),
                ('test', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.test')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
